Algoritmo "semnome"

Var

 user, password: caractere

Inicio

 escreva("digite o seu usuário: ")
 leia(user)
 escreva("digite sua senha: ")
 leia(password)
 
 enquanto (user<>"admin") ou (password<>"admin") faca
       escreval("usuario ou senha invlidos")
       escreva("digite o seu usuário: ")
       leia(user)
       escreva("digite sua senha: ")
       leia(password)
fimenquanto
 
escreval(" seja bem vindo ao sistema")


Fimalgoritmo